name: Run Postman Collection

on:
  push:
    branches:
      - master

jobs:
  run_postman_collection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Newman
      run: |
        sudo apt-get install curl
        sudo curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
        sudo apt-get install -y nodejs
        nodejs -v
        npm -v
        sudo npx install -g newman
        sudo chmod +x /usr/local/bin/newman

    - name: Run Postman Collection
      run: newman run pm_collection.json
