        
name: Flask App and Postman Collection

on:
    push:
      branches:
        - master

env:
  PYTHONPATH: /usr/local/lib/python3.8/site-packages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        virtualenv myenv
        source myenv/bin/activate
        pip install flask
        pip install flask-restful
        pip install jinja2

    - name: Run Flask app
      run: |
        export FLASK_APP=app.py
        flask run &
        echo $PYTHONPATH
        
    - name: Run ToDo project
      run: |
        source myenv/bin/activate
        /usr/bin/python3 /home/runner/work/todoapp/todoapp/todo.py

    - name: Install Newman
      run: |
        npm install -g newman

    - name: Run Postman Collection
      run: |
        newman run collection.json

