        
name: Flask App and Postman Collection

on:
    push:
      branches:
        - master

env:
  PYTHONPATH: /usr/local/lib/python3.11/site-packages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install Flask==1.1.2
        pip3 install flask-restful
        echo $PYTHONPATH

    - name: Run Flask app
      run: |
        export FLASK_APP=app.py
        flask run &
        echo $PYTHONPATH
        
    - name: Run ToDo project
      run: |
        /usr/bin/python3 /home/runner/work/todoapp/todoapp/todo.py

    - name: Install Newman
      run: |
        npm install -g newman

    - name: Run Postman Collection
      run: |
        newman run collection.json

