        
name: Flask App and Postman Collection

on:
    push:
      branches:
        - master

env:
  PYTHONPATH: /usr/local/lib/python3.8/site-packages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install virtualenv
      run: sudo apt-get install python3-virtualenv

    - name: Install dependencies
      run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install flask flask-restful
          
    - name: Add environment to PATH
      run: echo "export PATH=$PATH:$(pwd)/venv/bin" >> $GITHUB_ENV

    - name: Run Flask app
      run: |
        export FLASK_APP=app.py
        flask run &
        echo $PYTHONPATH
        
    - name: Run ToDo project
      run: |
        source myenv/bin/activate
        /usr/bin/python3 /home/runner/work/todoapp/todoapp/todo.py

    - name: Install Newman
      run: |
        npm install -g newman

    - name: Run Postman Collection
      run: |
        newman run collection.json

