name: Run Postman Collection

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: Install dependencies
      run: |
        cd todoapp
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install Flask
        pip3 install flask-restful

#     - name: Install Node.js and npm
#       run: |
#         sudo apt-get update
#         sudo apt-get install -y nodejs npm

    - name: Run ToDo project
      run: |
        /usr/bin/python /home/runner/work/todoapp/todoapp/todo.py

    - name: Install Newman
      run: |
        npm install -g newman

    - name: Run Postman Collection with Newman
      run: |
        newman run pm_collection.json
