name: Build Docker image
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          cd python_project
          docker build -t my-python-app .
          docker run -d -p 8080:8080 --name my-python-app my-python-app
          docker run --link my-python-app:myapp -v $(pwd)/newman:/etc/newman/ postman:v1 run pm_collection.json --env-var "url=http://myapp:8080"

      - name: Clean up Docker containers
        run: |
          docker stop my-python-app
          docker rm my-python-app
