name: Python Flask CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-app-image .

    - name: Run Docker container
      run: docker run my-app-image

    - name: Run Postman tests
      uses: postmanlabs/newman-action@v2.1.0
      with:
        collection: pm_collection.json
